### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by manish-karn** [erossini/BlazorMarkdownEditor#47]
e.replace is not a function
Please report this to https://github.com/markedjs/marked.
TypeError: e.replace is not a function
    at 15.n.code (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:262621)
    at t.parse (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:266244)
    at Function.parse (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:265492)
    at Function._ [as parse] (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:269941)
    at de.markdown (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:310443)
    at Object.previewRender (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:306325)
    at https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/markdownEditor.js:204:88
    at https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:46806
    at https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:76555
    at https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:76788
    at Zi (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:76814)
    at Io.setValue (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:81265)
    at de.value (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/easymde.min.js:7:324573)
    at setValue (https://localhost:7218/_content/PSC.Blazor.Components.MarkdownEditor/js/markdownEditor.js:312:25)
    at https://localhost:7218/_framework/blazor.server.js:1:3047
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7218/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (https://localhost:7218/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (https://localhost:7218/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (https://localhost:7218/_framework/blazor.server.js:1:51920)
    at s.onmessage (https://localhost:7218/_framework/blazor.server.js:1:80026)

**Comment by manish-karn** [comment]
this happen only when I have mermaid syntax in code, it is happening frequently

**Comment by manish-karn** [comment]
I saw this is closed, something I am still doing workaround, is there fix for it?

**Comment by erossini** [comment]
I think so. The new version of the JavaScript is rewritten and improved. Let me know if you still have the same error.

Thank you,
Enrico
________________________________
